config_registry:
  hardware: "configs/hardware.json"
  ibm_devices: "configs/ibm_devices.yaml"
  ionq_devices: "configs/ionq_devices.yaml"
  circuit_editor: "configs/editor_config.yaml"
  optimization: "configs/optimizer_config.yaml"
  code_switcher: "configs/switcher_config.yaml"
  logging_results: "configs/logging.yaml"
  workflow_policy: "configs/workflow_policy.yaml"
  analysis: "configs/analysis.yaml"
  profiler: "configs/profiler.yaml"
  multi_patch_rl_agent: "configs/multi_patch_rl_agent.yaml"
  gates: "configs/gates.yaml"
  ft_builder: "configs/ft_builder_config.yaml"
  code_families: "configs/code_families.yaml"
  qldpc_config: "configs/qldpc_config.yaml"
  compiler: "configs/compiler.yaml"