# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileCopyrightText: 2025 Dr. Debasis Mondal <deba10106@gmail.com>

default_max_qubits: 5
max_qubits: 50
grid_size: 40
color_scheme:
  background: "#0F2747"   # Dark blue
  wire: "#FFFFFF"         # White lines
  selected: "#2E86FF"     # Blue highlight