# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileCopyrightText: 2025 Dr. Debasis Mondal <deba10106@gmail.com>

enable_code_switching: true
export_formats:
  - qasm
  - json
  - yaml
code_switching_protocols:
  - name: magic_state_injection
    description: "Injects magic states for T gates."
    supported_gates: ["T", "Tdg"]
  - name: lattice_surgery
    description: "Lattice surgery for CNOT and other multi-qubit gates."
    supported_gates: ["CNOT"] 

# Preferences for non-transversal gate handling (used by policy/decision_policy.py)
non_transversal_preferences:
  prefer: magic_state_injection  # options: magic_state_injection, lattice_surgery, teleportation
  per_gate:
    T: magic_state_injection
    Tdg: magic_state_injection
    CCX: lattice_surgery
    CS: lattice_surgery
    CSdg: lattice_surgery