# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# SPDX-FileCopyrightText: 2025 Dr. Debasis Mondal <deba10106@gmail.com>

logging:
  level: INFO
  log_to_file: true
  log_file_path: logs/app.log
  log_to_stdout: true
results:
  storage_dir: results/
  export_formats: ["json", "csv", "yaml"] 